### ISSUE TITLE
Adjust the formatting to the npm standard

### ISSUE THREAD

**Issue by johannesschaefer** [ASzc/jsonpath-maven-plugin#5]
Currently this tool adds spaces after the value (e.g. dependency name in package.json) and before the colon. NPM has no space at the spaces.
This makes it difficult to compare later the changes with diff tools.

I would be great if the formatting is adjustable or at least that it fits to the npm standard.

**Comment by ASzc** [comment]
I'll see how easy it is to make this tweak to the default PrettyPrinter.

**Comment by ASzc** [comment]
I've implemented a new formatter in #6. It'll produce output that is formatted like [this file](https://github.com/keycloak/keycloak-nodejs-connect/blob/master/package.json). Please let me know if that works for you.

**Comment by johannesschaefer** [comment]
Hi,
thanks for you fast fix. I just tested it an it look good.
So, from my point of view please do an release. :-)

**Comment by ASzc** [comment]
1.2.0 has been released with this feature and will be available from central within a few hours.
